language: node_js
node_js:
  - "0.10"
  - "4.*"
  - "5.*"
before_install:
  - ./build_etcd.sh v0.3.0
before_script: "./etcd/bin/etcd &"
after_script: nyc report --reporter=text-lcov | coveralls
env: TRAVIS=True
sudo: false
