language: node_js
node_js:
  - "0.10"
  - "iojs"
  - "4.*"
  - "5.*"
before_install:
  - ./build_etcd.sh v0.3.0
before_script: "./etcd/bin/etcd &"
after_script: "NODE_ENV=test YOURPACKAGE_COVERAGE=1 ./node_modules/.bin/mocha --require blanket --reporter mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js"
env: TRAVIS=True
sudo: false
